name: Typecheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: typecheck-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Prepare Nuxt
        run: pnpm nuxt prepare

      - name: Run Typechecker
        run: pnpm typecheck
